
INSERT INTO countries(name,countryCode,region) VALUES ('Afghanistan','AF','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Aland Islands','AX','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Albania','AL','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Algeria','DZ','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('American Samoa','AS','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Andorra','AD','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Angola','AO','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Anguilla','AI','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Antarctica','AQ','Polar');
INSERT INTO countries(name,countryCode,region) VALUES ('Antigua And Barbuda','AG','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Argentina','AR','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Armenia','AM','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Aruba','AW','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Australia','AU','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Austria','AT','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Azerbaijan','AZ','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Bahamas The','BS','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Bahrain','BH','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Bangladesh','BD','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Barbados','BB','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Belarus','BY','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Belgium','BE','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Belize','BZ','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Benin','BJ','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Bermuda','BM','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Bhutan','BT','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Bolivia','BO','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Bosnia and Herzegovina','BA','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Botswana','BW','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Bouvet Island','BV',NULL);
INSERT INTO countries(name,countryCode,region) VALUES ('Brazil','BR','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('British Indian Ocean Territory','IO','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Brunei','BN','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Bulgaria','BG','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Burkina Faso','BF','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Burundi','BI','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Cambodia','KH','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Cameroon','CM','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Canada','CA','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Cape Verde','CV','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Cayman Islands','KY','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Central African Republic','CF','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Chad','TD','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Chile','CL','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('China','CN','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Christmas Island','CX','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Cocos (Keeling) Islands','CC','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Colombia','CO','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Comoros','KM','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Congo','CG','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Congo The Democratic Republic Of The','CD','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Cook Islands','CK','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Costa Rica','CR','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Cote D''Ivoire (Ivory Coast)','CI','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Croatia (Hrvatska)','HR','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Cuba','CU','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Curaçao','CW','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Cyprus','CY','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Czech Republic','CZ','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Denmark','DK','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Djibouti','DJ','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Dominica','DM','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Dominican Republic','DO','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('East Timor','TL','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Ecuador','EC','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Egypt','EG','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('El Salvador','SV','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Equatorial Guinea','GQ','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Eritrea','ER','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Estonia','EE','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Ethiopia','ET','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Falkland Islands','FK','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Faroe Islands','FO','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Fiji Islands','FJ','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Finland','FI','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('France','FR','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('French Guiana','GF','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('French Polynesia','PF','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('French Southern Territories','TF','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Gabon','GA','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Gambia The','GM','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Georgia','GE','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Germany','DE','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Ghana','GH','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Gibraltar','GI','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Greece','GR','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Greenland','GL','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Grenada','GD','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Guadeloupe','GP','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Guam','GU','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Guatemala','GT','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Guernsey and Alderney','GG','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Guinea','GN','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Guinea-Bissau','GW','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Guyana','GY','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Haiti','HT','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Heard and McDonald Islands','HM',NULL);
INSERT INTO countries(name,countryCode,region) VALUES ('Honduras','HN','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Hong Kong S.A.R.','HK','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Hungary','HU','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Iceland','IS','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('India','IN','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Indonesia','ID','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Iran','IR','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Iraq','IQ','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Ireland','IE','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Israel','IL','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Italy','IT','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Jamaica','JM','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Japan','JP','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Jersey','JE','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Jordan','JO','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Kazakhstan','KZ','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Kenya','KE','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Kiribati','KI','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Korea North','KP','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Korea South','KR','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Kosovo','XK','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Kuwait','KW','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Kyrgyzstan','KG','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Laos','LA','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Latvia','LV','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Lebanon','LB','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Lesotho','LS','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Liberia','LR','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Libya','LY','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Liechtenstein','LI','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Lithuania','LT','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Luxembourg','LU','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Macau S.A.R.','MO','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Macedonia','MK','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Madagascar','MG','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Malawi','MW','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Malaysia','MY','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Maldives','MV','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Mali','ML','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Malta','MT','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Man (Isle of)','IM','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Marshall Islands','MH','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Martinique','MQ','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Mauritania','MR','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Mauritius','MU','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Mayotte','YT','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Mexico','MX','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Micronesia','FM','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Moldova','MD','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Monaco','MC','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Mongolia','MN','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Montenegro','ME','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Montserrat','MS','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Morocco','MA','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Mozambique','MZ','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Myanmar','MM','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Namibia','NA','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Nauru','NR','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Nepal','NP','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Netherlands Antilles','AN',NULL);
INSERT INTO countries(name,countryCode,region) VALUES ('Netherlands The','NL','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('New Caledonia','NC','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('New Zealand','NZ','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Nicaragua','NI','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Niger','NE','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Nigeria','NG','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Niue','NU','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Norfolk Island','NF','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Northern Mariana Islands','MP','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Norway','NO','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Oman','OM','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Pakistan','PK','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Palau','PW','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Palestinian Territory Occupied','PS','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Panama','PA','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Papua new Guinea','PG','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Paraguay','PY','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Peru','PE','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Philippines','PH','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Pitcairn Island','PN','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Poland','PL','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Portugal','PT','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Puerto Rico','PR','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Qatar','QA','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Reunion','RE','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Romania','RO','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Russia','RU','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Rwanda','RW','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Saint Helena','SH','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Saint Kitts And Nevis','KN','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Saint Lucia','LC','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Saint Pierre and Miquelon','PM','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Saint Vincent And The Grenadines','VC','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Saint-Barthelemy','BL','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Saint-Martin (French part)','MF','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Samoa','WS','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('San Marino','SM','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Sao Tome and Principe','ST','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Saudi Arabia','SA','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Senegal','SN','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Serbia','RS','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Seychelles','SC','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Sierra Leone','SL','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Singapore','SG','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Slovakia','SK','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Slovenia','SI','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Solomon Islands','SB','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Somalia','SO','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('South Africa','ZA','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('South Georgia','GS','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('South Sudan','SS','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Spain','ES','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Sri Lanka','LK','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Sudan','SD','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Suriname','SR','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Svalbard And Jan Mayen Islands','SJ','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Swaziland','SZ','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Sweden','SE','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Switzerland','CH','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Syria','SY','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Taiwan','TW','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Tajikistan','TJ','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Tanzania','TZ','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Thailand','TH','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Togo','TG','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Tokelau','TK','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Tonga','TO','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Trinidad And Tobago','TT','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Tunisia','TN','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Turkey','TR','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Turkmenistan','TM','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Turks And Caicos Islands','TC','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Tuvalu','TV','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Uganda','UG','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Ukraine','UA','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('United Arab Emirates','AE','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('United Kingdom','GB','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('United States','US','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('United States Minor Outlying Islands','UM','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Uruguay','UY','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Uzbekistan','UZ','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Vanuatu','VU','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Vatican City State (Holy See)','VA','Europe');
INSERT INTO countries(name,countryCode,region) VALUES ('Venezuela','VE','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Vietnam','VN','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Virgin Islands (British)','VG','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Virgin Islands (US)','VI','Americas');
INSERT INTO countries(name,countryCode,region) VALUES ('Wallis And Futuna Islands','WF','Oceania');
INSERT INTO countries(name,countryCode,region) VALUES ('Western Sahara','EH','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Yemen','YE','Asia');
INSERT INTO countries(name,countryCode,region) VALUES ('Zambia','ZM','Africa');
INSERT INTO countries(name,countryCode,region) VALUES ('Zimbabwe','ZW','Africa');
